development:
  CONSUMER_KEY: ebKB0UKwR2iZ6hCC7LiERQ
  CONSUMER_SECRET: vkzJZVLULwxFbZt1arey4FzW34cPJNlFZCv3pmUz9A

test:
  CONSUMER_KEY: ebKB0UKwR2iZ6hCC7LiERQ
  CONSUMER_SECRET: vkzJZVLULwxFbZt1arey4FzW34cPJNlFZCv3pmUz9A
  
production:
  CONSUMER_KEY: ebKB0UKwR2iZ6hCC7LiERQ
  CONSUMER_SECRET: vkzJZVLULwxFbZt1arey4FzW34cPJNlFZCv3pmUz9A